### ISSUE TITLE
Questions about train bandwidth

### ISSUE THREAD

**Issue by chengcheng8632** [facebookresearch/mvfst-rl#23]
Dear Author:
     Sorry to bother you again, because the mvfst-rl model is used in different environments for congestion control, the model needs to be retrained. But when we expand the training trace bandwidth to more than 500M, our RL model cannot be trained, and the entire training process cannot run. Have you tried training with a larger bandwidth? The reasons for not being trained should be analyzed from what aspects. Looking forward to your answer, thank you very much.

**Comment by odelalleau** [comment]
Hi @chengcheng8632,
So far we've been using the traces from the `train/traces` folder, which go up to 115 Mbps. Could you please describe how you generated the 500 Mbps trace? (and maybe upload it here so that we can test it ourselves). Thanks!

**Comment by chengcheng8632** [comment]
Hi@odelalleau,
According to the meaning of the trace , each line in the trace represents the time (in milliseconds) required to transmit a 1500-byte MTU, and a 500mbps.trace is made and placed in my github(https://github.com/chengcheng8632/trace). We hope you can test it, thank you very much!

**Comment by odelalleau** [comment]
Thanks, I'll have a look!

**Comment by odelalleau** [comment]
I launched a quick training and it seems to be working for me (reward is going up over time). Can you please provide more details regarding what you mean by "our RL model cannot be trained"?

**Comment by chengcheng8632** [comment]
Hi@odelalleau,
I only used the bandwidth of 1000mbps.trace to generate training environments with different delays. The training process is given in the attachment. It can be updated at the beginning, but later the tunnelclient cannot receive the information, which causes the training to fail. At the same time, throughput and cwnd and reward look not normal. So, I want to know the settings of your training environment, and  can you give me your training process? Thank you very much!
[test_1000.log](https://github.com/facebookresearch/mvfst-rl/files/4358245/test_1000.log)

**Comment by odelalleau** [comment]
Ok I see. On my side I'm also seeing similar errors but much less frequently so they don't actually block training (when it fails it just moves on to the next episode), while in your case it seems like nothing is working anymore.

One thing I would suggest is to reduce the numbers of actors. Right now I'm actually running with only 10 actors instead of 40 because I'm running into other issues with 40 (not the same as yours). It's possible that 40 actors at 1000mbps may induce too much load on your system.

**Comment by chengcheng8632** [comment]
Hi @ odelalleau，
Thank you very much for your answer. Now I only use 5 actors for training, but I still have some problems. 
First, during training, the value of loss is always large. I observe the entire training process, the value of total_loss does not seem to have converged. may I ask if this is normal? 
Second, for our calculation formula for throughput, we use the CWND / RTrtt_STANDING calculation method. How should we understand this? I'm a little confused. Under the large bandwidth, whether the sharp increase of CWND will bring about a rapid increase in throughput and thus form a vicious circle.
Third, is it possible to use the calculation method (receivedBytes / duration_.count) of receiving data divided by the receiving time at the receiving end. I don't know what the difference between these two calculation methods will be, can I try? 
Looking forward to your reply, thank you very much!

**Comment by odelalleau** [comment]
Hi @chengcheng8632,

Let me try to address your 3 questions:

1. This is a common phenomenon in RL because the optimization target changes over time as the critic is updated, due to bootstrapping of the critic's estimate. Another reason why this may happen is due to the agent discovering new states (the training data distribution is not stationary). So I would not worry too much about that.

2. CWND / RTT_STANDING is the formula used in the Copa paper (https://www.usenix.org/system/files/conference/nsdi18/nsdi18-arun.pdf), see section 2.1. To understand it, consider that since there are CWND packets in flight at any given time, it means that we are able to send CWND packets before the first one is acknowledged, which is the RTT (estimated here with the RTT_STANDING formula). In other words, we are sending CWND packets in RTT_STANDING seconds, which gives a throughput in packets/s

3. Could you clarify precisely how you would obtain "receivedBytes" and  "duration_.count" in the code? If I understand correctly this should indeed give you the throughput as seen from the receiver's PoV, but in a different unit (bytes/s instead of packets/s). I expect that the main difference should come from packet loss, since the CWND / RTT_STANDING formula ignores it.
