### ISSUE TITLE
Problem when running RL-server and Client

### ISSUE THREAD

**Issue by Zyangzzz** [facebookresearch/mvfst-rl#33]
When RUNNING a server that uses reinforcement learning congestion control algorithms, I ran into a small problem using 'models/traced_model.pt' and' LOCAL 'modes,

```
I1123 15:53:53.327754 1776259 RLCongestionControllerFactory.h:36] Creating RLCongestionController
I1123 15:53:53.328002 1776259 CongestionControlLocalEnv.cpp:21] Loading traced model from /home/ustc-4/mvfst-rl/models/traced_model.pt
I1123 15:53:53.362632 1776259 tperf.cpp:420] Starting sends to client.
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "code/traced_model.py", line 24, in forward
  _9, x, _10, = torch.values(argument_1)
  _11, _12, = argument_2
  T = ops.prim.NumToTensor(torch.size(x, 0))
                           ~~~~~~~~~~ <--- HERE
  _13 = int(T)
  _14 = int(T)
RuntimeError: dim() called on undefined Tensor
```
I try to fing out the error, but there is not too much information in file 'traced_model.pt'. I wondered if it is due to a mismatch between the run-time input and github's 'models/traced_model.pt'. I'd appreciate any Pointers.

**Comment by odelalleau** [comment]
I'm going to look into it, but it would be helpful if you could please provide:
1. Your current revision
2. The command line used for the tperf server
3. The command line used for the tperf client
Thanks!

**Comment by odelalleau** [comment]
So, I looked into it, a few comments:

1. It turns out that contrary to what I thought, this model hadn't been updated yet in this public repository. Now I remember what happened: I had originally forgotten to update the model when updating the code, and after realizing my mistake, I wasn't entirely sure whether I wanted to push a new model or just remove the old one. The reason is that at ~10 Mb per model, the repo size can quickly grow quite large if we keep updating it. So I'm currently leaning towards just removing it, and instead providing some command lines to regenerate it (keeping in mind that since training isn't deterministic, it's impossible to regenerate it exactly).
2. In the meantime, if you really need it I could make it available to you outside of the main branch -- please just confirm your current revision so that I can make sure it works at that revision first.
3. FYI that model would be the one used to report results in the current (v4) version of https://arxiv.org/abs/1910.04054. It's not a particularly good model -- it works reasonably well in some settings but, as explained in the paper, it also fails in some others. We have a more recent model that works significantly better (though on a limited range of network conditions), but it's based on an internal version of the code that's not quite ready for release (no ETA yet due to other priorities).
4. Side note: I'm surprised you're getting a Python traceback since tperf is supposed to use only the C++ API. When I run it myself I get a different (full C++) error. Not sure what happened here (?)
5. I'm not sure what your objective is with using tperf, but FYI if you want to run meaningful congestion control tests you should run it over a network interface with limited bandwidth (by default if you run both the server and client locally it will use the local interface which is ultra fast). You can use for instance the `tc` tool for this purpose.

Hope this helps!

**Comment by Zyangzzz** [comment]
Thank you very much for your reply!
I made following changes:
in 'mvfst-rl/third-party/mvfst/quic/congestion_control/CongestionControlLocalEnv.cpp'
line 81 to line 83:
```cpp
quic::utils::vector<torch::IValue> inputs{std::move(last_action_tensor),
                                          std::move(env_inputs),
                                          std::move(core_state)};
const auto &outputs = module_.forward(inputs).toTuple();
```
changed into:
```cpp
c10::Dict<std::string,torch::Tensor> input_dict;
//input_dict.insert("last_action",std::move(last_action_tensor));
input_dict.insert("obs",tensor_.reshape({1, -1}));
input_dict.insert("reward",std::move(reward_tensor));
input_dict.insert("done",std::move(done_tensor));                           
quic::utils::vector<torch::IValue> inputs{std::move(input_dict),
                                          std::move(core_state)};                                          
const auto &outputs = module_.forward(inputs).toTuple();
```
Before I modify this code, there is an error like this:
```
terminate called after throwing an instance of 'c10::Error'
  what():  Expected at most 3 argument(s) for operator 'forward', but received 4 argument(s). Declaration: forward(__torch__.traced_model self, Dict(str, Tensor) argument_1, (Tensor, Tensor) argument_2) -> (((Tensor, Tensor, Tensor), (Tensor, Tensor)))
Exception raised from checkAndNormalizeInputs at ../aten/src/ATen/core/function_schema_inl.h:245 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fffe67b4b89 in /home/ustc-4/mvfst-rl/_build/deps/libtorch/lib/libc10.so)
frame #1: <unknown function> + 0xbc5727 (0x7fffe75a7727 in /home/ustc-4/mvfst-rl/_build/deps/libtorch/lib/libtorch_cpu.so)
frame #2: torch::jit::GraphFunction::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0x2d (0x7fffe978193d in /home/ustc-4/mvfst-rl/_build/deps/libtorch/lib/libtorch_cpu.so)
frame #3: torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0x16f (0x7fffe979272f in /home/ustc-4/mvfst-rl/_build/deps/libtorch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0xa0d7d (0x5555555f4d7d in ./_build/build/traffic_gen/traffic_gen)
frame #5: <unknown function> + 0xc9039 (0x7fffe64b6039 in /home/ustc-4/miniconda3/envs/mvfst-rl/lib/libstdc++.so.6)
frame #6: <unknown function> + 0x9609 (0x7ffff73a5609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #7: clone + 0x43 (0x7fffe61b8293 in /lib/x86_64-linux-gnu/libc.so.6)

```
And the command line used for the tperf server
```cpp
./third-party/mvfst/_build/build/quic/tools/tperf/tperf \
	-mode=server \
	-host=20.0.0.4 \
	-port=11116 \
	-congestion=rl \
	-gso=true \
	-pacing=true \
	-max_cwnd_mss=86000000 \
	-window=655360000 \
	-writes_per_loop=64 \
	-num_server_worker=1 \
	-cc_env_model_file=/home/ustc-4/mvfst-rl/models/traced_model.pt 
```
The command line used for the tperf client
```cpp
./_build/build/quic/tools/tperf/tperf \
  -mode=client \
  -host=20.0.0.4 \
  -port=11116 \
  -congestion=none \
  -max_cwnd_mss=8600000 \
  -window=655360000 \
  -duration=30

```

**Comment by odelalleau** [comment]
Thanks for the extra info (though please also provide the revision commit ID to be 100% sure I can test at the same revision, since there are multiple branches in this repo)

Just a note regarding the tperf server command line: be careful that some additional settings may need to be provided on the command line, depending on how the model was trained and the default values in tperf.cpp (unfortunately this isn't yet done automatically). If you unpickle `models.traced_model.flags.pkl` and look for flags starting with `cc_env_*`, those are typically the ones that should be provided to tperf.
(this won't solve the problem that the current model in the repo is a veeeeery old one and it's pointless to try to get it to run)

**Comment by Zyangzzz** [comment]
Well，I just found something strange. After I unpickled `models.traced_model.flags.pkl` , I found the `cc_env_mode:remote`.However, `cc_env_mode = remote` is not suported in `tperf.cpp`.
```cpp
  if (FLAGS_cc_env_mode == "local") {
    cfg.mode = Config::Mode::LOCAL;
  } else if (FLAGS_cc_env_mode == "remote") {
    LOG(FATAL) << "Remote RL env is not currently supported";
  } else if (FLAGS_cc_env_mode == "random") {
    cfg.mode = Config::Mode::RANDOM;
  } else if (FLAGS_cc_env_mode == "fixed") {
    cfg.mode = Config::Mode::FIXED;
  } else {
    LOG(FATAL) << "Unknown cc_env_mode: " << FLAGS_cc_env_mode;
  }
```

**Comment by odelalleau** [comment]
> Well，I just found something strange. After I unpickled `models.traced_model.flags.pkl` , I found the `cc_env_mode:remote`.However, `cc_env_mode = remote` is not suported in `tperf.cpp`.

Oh yeah sorry, that one must be set to `local` when using tperf. The idea is that you're using `remote` during training, then `local` for evaluation.

**Comment by odelalleau** [comment]
Hi, I'm going to close this issue since I believe your questions have been answered (please reopen or open a new issue if that isn't the case). A few remarks:

1. The project is not actively maintained anymore (this means there may be no more updates, and support may take longer than usual)

2. I suggest that you switch to the v4 branch (or the mtenv branch if you want to use the MTEnv wrapper). These branches contain the latest version of the code, where some reasonably good results have been obtained.

3. I'm providing below a command line I used to train one of our best models (much better than the latest results in the Arxiv paper), in case it might be useful to you or others:

```
python3 -m train.train \
mode=train \
test_after_train=false \
jobs@train_jobs=random_traces_3_5 \
jobs@eval_jobs=fixed_0_5 \
num_actors=20 \
num_actors_eval=2 \
train_job_ids="[0]" \
eval_job_ids="[3,4,5]" \
total_steps=13_000_000 \
hidden_size=256 \
unroll_length=8 \
inference_batch_size=1 \
seed=1,2 \
use_lstm=true \
use_reward=false \
shared_actor_critic=true \
activations='[tanh,tanh]' \
use_task_obs_in_actor=false \
use_task_obs_in_critic=true \
end_of_episode_bootstrap=true \
entropy_cost=5e-3 \
baseline_cost=0.5 \
discounting=0.95 \
reward_clipping=none \
reward_normalization=false \
reward_normalization_coeff=1e-4 \
reward_normalization_stats_per_job=false \
learning_rate=5e-4 \
alpha=0.99 \
momentum=1e-4 \
empirical_base_rtt=true \
cc_env_norm_bytes=1000000 \
cc_env_norm_ms=100 \
cc_env_history_size=4 \
cc_env_reward_delay_factor=1 \
cc_env_reward_delay_log_offset=1e-5 \
cc_env_reward_packet_loss_factor=0 \
cc_env_reward_formula=cwnd_tradeoff \
cc_env_reward_uplink_queue_max_fill_ratio=0.5 \
cc_env_reward_delay_offset=0 \
cc_env_reward_min_throughput_ratio=0.9 \
cc_env_reward_n_packets_offset=1 \
cc_env_bandwidth_min_window_duration_ms=100 \
cc_env_ack_delay_avg_coeff=0.1 \
-m
```
