### ISSUE TITLE
Pantheon sprout protobuf incompatible when running ./setup.sh

### ISSUE THREAD

**Issue by Zongshen** [facebookresearch/mvfst-rl#34]
Hello! Thank you for providing this highly integrated platform.
I tried to build the project in the conda environment with py3.8 in Ubuntu 20.04LTS.
However, I met the protobuf incompatibility errors when building sprout in _build/deps/pantheon.
The error log says as 
"userinput.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
   12 | #error This file was generated by a newer version of protoc which is
... ...
... ..."

Pantheon requires Python 2.7, but in its pantheon/src/wrappers/sprout.py --setup, it says it needs to use conda version of protobuf.
However, my current python env setup is:
      base: python-2.7 , protoc-3.6.1 
      mvfst-rl conda: python-3.8 , protoc-3.8.0
Thus, I think pantheon currently uses python-2.7 in base while uses protoc-3.8.0 in conda.
May I know how to solve this problem?

Thank you again.

**Comment by odelalleau** [comment]
Hi, sorry my bandwidth is limited (this project isn't actively supported anymore) so it may take me a few days to look into it.

Pantheon indeed uses Python 2.7 but this shouldn't really matter to compile sprout (which is in C/C++). For soome reason it looks like it's using one version of protobuf for code generation, and another one for compilation. Probably some kind of PATH / CPATH issue.

Can you let me know what happens if you run the following commands in your mvfst-rl  conda env:
```
cd _build/deps/pantheon/third_party/sprout
rm -rf compile src && git checkout -- .
cd ../..
python2 ./src/experiments/setup.py --setup --schemes sprout
```

**Comment by Zongshen** [comment]
Hi, Olivier. Really appreciate your response. 
I run those commands in the mvfst-rl conda env and it seem that Pantheon compiles now. (although with some warnings)

`make[3]: Entering directory '/home/zongshen/Project/mvfst-rl/_build/deps/pantheon/third_party/sprout/src/protobufs`
 ` GEN      userinput.pb.cc`
`  GEN      hostinput.pb.cc`
`  GEN      transportinstruction.pb.cc`
`  GEN      sproutmath.pb.cc`
`  GEN      deliveryforecast.pb.cc`
`[libprotobuf WARNING google/protobuf/compiler/parser.cc:637] No syntax specified for the proto file: hostinput.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)`
`[libprotobuf WARNING google/protobuf/compiler/parser.cc:637] No syntax specified for the proto file: userinput.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)`
`[libprotobuf WARNING google/protobuf/compiler/parser.cc:637] No syntax specified for the proto file: sproutmath.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)`

After this, I run `./setup.sh` in mvfst-rl conda env again. However, I got the following pthread configuration error when compiling mvfst.

`Building C object CMakeFiles/cmTC_b4ca3.dir/src.c.o`
`/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_b4ca3.dir/src.c.o -c /home/zongshen/Project/mvfst-rl/third-party/mvfst/_build/deps/folly/build/CMakeFiles/CMakeTmp/src.c`
`Linking C executable cmTC_b4ca3`
`/home/zongshen/anaconda3/envs/mvfst-rl/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b4ca3.dir/link.txt --verbose=1`
`/usr/bin/cc -rdynamic CMakeFiles/cmTC_b4ca3.dir/src.c.o -o cmTC_b4ca3`
`/usr/bin/ld: CMakeFiles/cmTC_b4ca3.dir/src.c.o: in function 'main':`
`src.c:(.text+0x46): undefined reference to 'pthread_create'`
`/usr/bin/ld: src.c:(.text+0x52): undefined reference to 'pthread_detach'`
`/usr/bin/ld: src.c:(.text+0x5e): undefined reference to 'pthread_cancel'`
`/usr/bin/ld: src.c:(.text+0x6f): undefined reference to 'pthread_join'`
`collect2: error: ld returned 1 exit status`

May I know where should I change?

Thank you so much.

**Comment by odelalleau** [comment]
Don't worry about the warnings when compiling sprout, there are tons of warnings everywhere, as long as it compiles you should be good.

The error while compiling mvfst is more annoying and not something I can directly help you with, because it's working fine on my system. My suggestion would be to:
1. Try to clone and compile the "official" version of mvfst from https://github.com/facebookincubator/mvfst to make sure it's working fine (if you run into the same issue, then you need to figure out how to fix it)
2. If the latest "official" version compiles, then (after cleaning build files) try with commit d6ed8042 which is the older version mvfst-rl is currently based on. If it fails then it gives a hint that you need to update to a more recent mvfst, so you'd need to rebase the mvfst-rl custom commits on top of a more recent version

**Comment by Zongshen** [comment]
No problem. Thank you for your time and suggestion.

**Comment by odelalleau** [comment]
> No problem. Thank you for your time and suggestion.

You're welcome! Don't hesitate to share your findings here if you manage to get it fixed, and to let me know if you need further help.

**Comment by Zongshen** [comment]
Hi Olivier, I tried with the latest version of the mvfst and I got QuicBatchWriterTest errors.
However, after I switched back to try building mvfst-rl again, the mvfst in mvfst-rl seems to work.
The final lines of the building output are mentioned in #35 .
But when I try to run the `python3 -m train.train`
I got the error saying that `the module 'nest' has no attribute 'map' ` #35 
Could you please help me with this if possible?
Thank you again.

**Comment by odelalleau** [comment]
> Hi Olivier, I tried with the latest version of the mvfst and I got QuicBatchWriterTest errors. However, after I switched back to try building mvfst-rl again, the mvfst in mvfst-rl seems to work.

It's weird that it would suddenly work without changing anything... But anyway, good for you if the build succeeded :)
I'll reply in the other issue for the nest error.
