### ISSUE TITLE
Encounter an error when running script setup.sh

### ISSUE THREAD

**Issue by cczaqq** [facebookresearch/mvfst-rl#36]
Hello! Thank you for providing this highly integrated platform.
I tried to build the project in the conda environment with python in Ubuntu 20.04LTS.
However, when I run setup.sh, the following error appears：
”
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
“

Why? And how to solve the problem?
Thans a lot!

**Comment by odelalleau** [comment]
Can you provide more context to be able to identify which github repo is failing here?

There are most likely two potential ways to fix this issue:
1. Make sure you have properly setup a github key (https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)
2. Or, simply use `https` instead of the `ssh` git protocol. So for instance, if it's related to Pantheon, replace `git clone -b mvfst-rl git@github.com:odelalleau/pantheon.git "$PANTHEON_DIR"` with `git clone -b mvfst-rl https://github.com/odelalleau/pantheon.git "$PANTHEON_DIR"`

**Comment by cczaqq** [comment]
I replace git clone -b mvfst-rl git@github.com:odelalleau/pantheon.git "$PANTHEON_DIR" with git clone -b mvfst-rl https://github.com/odelalleau/pantheon.git "$PANTHEON_DIR", it works.

Thanks a lot!

**Comment by odelalleau** [comment]
Closing issue since the workaround above is working
